version: '2'

networks:
  openplatform:

services:
  exporter:
    container_name: redisearch-exporter
    environment:
      - ADDR=redis://localhost:6379
    ports:
      - "9122:9122"
  redis01:
    container_name: redis01
    image: redislabs/redisearch:2.0.12
    ports:
      - "6379:6379"
    networks:
      - openplatform